# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fR1YdTOu4EB84azMgGMxXMuZx1U0ge83
"""

class Cuenta:
  def __init__(self):
    self.saldo = 0

  def depositar(self, monto):
    self.saldo += monto

  def retirar(self, monto):
    if monto <= self.saldo:
      self.saldo -= monto
    else:
      print("Fondos insuficientes")

  def mostrar_saldo(self):
    print(f"Saldo actual: {self.saldo}")